### PR TITLE
Adding USB HID support contributions from akudaikon

### PR DESCRIPTION
**Pull request by jpconstantineau**
Note that to support USB HID, you need to compile with the Community BSP and not the Adafruit BSP.

### CODE REVIEW

**Comment by akudaikon** [comment]
A couple comments just to explain why I did what I did...

In USB/BLE switch logic in firmware_main.cpp:
> //Battery::first_vbat = true;
> //KeyScanner::setLastPressed(millis());  // why here?
> //keyboardstate.timestamp = millis();    // why here?

- I added a battery voltage filter to try to smooth out the ADC readings and get a more consistent battery reading. When you switch from USB to BLE (or vise versa), the ADC reading switches from USB Vdd to battery voltage. Instead of waiting for the filter to slowly catch up to the new voltage, I use the first_vbat flag to reset the filter.
- The setLastPressed and keyboardstate.timestamp values are updated on connection state change because USB doesn't have a sleep timeout, but BLE does. So say for example you're on USB and haven't pressed a key in 1 minute. Then you unplug USB to switch over to BLE. The unconnected BLE sleep timeout is 30 seconds. This will cause the keyboard to immediately go to sleep. So I reset those values ("fake" a keypress) on connection state change to ensure that doesn't happen.
- There are probably much better ways to handle both of these things than my hacky approach.

BLE profile switch combos in firmware_main.cpp:
> // if (keyboardstate.connectionState != CONNECTION_USB) // can we switch BLE profile when connected to USB???

- This is just an arbitrary decision on my part. There's no reason why you couldn't switch the BLE profile while connected to USB. I just didn't think it was necessary, and it causes a system reset when it happens too, which would cause a USB reconnect.

**Comment by jpconstantineau** [comment]
@akudaikon Thanks for the heads up on these items.

I left out the battery filtering but did include the check on sleep and now prevent switching BLE profile when connected to USB.  I called the variable a "last user action timestamp" and unplugging is indeed an action. 

I agree with you that a reboot of the keyboard would cause annoying USB reconnects just for a switch of the BLE Profile; even though we are not typing through BLE...

For battery filtering/calculations, I am thinking of setting up some kind of callback that the user could use to  override the default battery calculations.  This could be where filtering/switching could be done.

I think I am getting close but still need to test it all out on a board and also test on a split board.  Take for example, what happens when USB is connected on the slave side...  That might be a trickier case...

**Comment by mpaupulaire4** [comment]
I would be happy to help test on split keyboard as this is my use case.

**Comment by jpconstantineau** [comment]
Yes, that would be helpful.  With holidays in the past and me back at work, my time is quite limited.  If you could first try the branch and specifically the left connected to USB/BLE and see if it all works fine.

Once that is validated, we will need to check the right (slave) half.  

The expectation is for the Profiles and BLE/USB switch keycodes to be coded on the LEFT.  If they are coded on the RIGHT, they won't work properly. As such, I will need to "disable" these keycode on the Right Halves.

**Comment by serialx** [comment]
I've just tried this PR onto my keyboard. USB HID doesn't work. (It's a simple HHKB variant)

Looking at the code, the USB HID is not actually initialized in the firmware code. Please verify if this PR is not in a working state?
Happy to help, although Arduino/firmware development is not my expertise.

**Comment by jpconstantineau** [comment]
@serialx Which BSP are you using?  By default, not to break everyone's compilation, I opted to include the libraries  through the Community BSP.  This allowed me to check for which BSP and opt in the features that require additional libraries when compiled with the Community BSP.  Give a try at installing the other BSP (see instructions [here](https://github.com/jpconstantineau/Community_nRF52_Arduino/wiki/Installation-Instructions)) and let me know if that works out better.

**Comment by serialx** [comment]
image

I've also changed the macos build script to use community_nrf52 fqbn instead of adafruit's one.
Also confirmed TINYUSB_AVAILABLE is defined.

I cannot find any code that calls usb_setup() or usb_sendKeys(.....) in the code.

**Comment by jpconstantineau** [comment]
Let me check if I did push my last changes to the PR.

**Comment by serialx** [comment]
NVM, I've used the 2 week old version of akudaikon-usb branch. Sorry for the mishap. Will test again.

**Comment by serialx** [comment]
Checked with the latest branch. USB HID works like a charm. But mine is not a split keyboard, so can't help you with that.

I'm using this keyboard daily at work and at home. I'll report if there's any problem regarding this branch.

Also if you need any help, I'd be happy to help!

Thank you!

**Comment by jpconstantineau** [comment]
Great. Thanks for the help.

**Comment by serialx** [comment]
Have the debouncing logic changed? I've noticed high error rates during typing is this branch. DEBOUNCETIME changed to 1 (from 5). The error is noticabel at very fast speeds (600 CPM)

I'm currently at a somewhat stable state using DEBOUNCETIME=5 and HIDREPORTINGINTERVAL=1. But still nowhere stable as the master branch I've used two weeks ago.

**Comment by jpconstantineau** [comment]
You can change it back to 5 and let me know. Some people have been
experimenting bringing it down.

**Comment by serialx** [comment]
Test results with DEBOUNCETIME=5 and HIDREPORTINGINTERVAL=8

Keys sometimes don't register to the computer
Keys sometimes gets stuck in the pressed statate, resulting in massive repeated key presses in the PC.

I guess this may be not related to debouncing logic? If I press PRINT_INFO results are like below:

```
Keyboard Name : My HHKB 
Keyboard Model : My HHKB 0.2 oard Mfg : serialx 
BSP Library .0.1 
Bootl : s140 6.1.1
Serial No : D88CBEC517372E5BDevice Power : 0.000000
CONNECTION_MODE_USB_ONLYCONNECTION_USB
```

Clearly show missing characters there.

**Comment by jpconstantineau** [comment]
When connected by BLE, missing and non-stop repeated keys are symptoms of
poor radio signal strength causing poor communication with the computer.

When connected to USB, this cannot be the case. As such, it seems that some
HID reports are not being sent.

**Comment by serialx** [comment]
Yes above testing was done by USB.

**Comment by serialx** [comment]
I've ported my keyboard to ZMK to see if the issue was related to my keyboard.

In ZMK, key press loss or key getting stuck doesn't happen.
I think there's something going on with HID reports? Don't have a clear view.

**Comment by jpconstantineau** [comment]
I finally installed a BlueMicro840 in my luddite to really get longer term usage on USB.  I did also get repeated keys as @serialx saw.

**Comment by jpconstantineau** [comment]
@serialx I just got the repeated keys issue running on BLE only from my luddite.  As such, it's the debounce parameters that moved from 5 down to 1 that's likely the problem.  I never had that issue on BLE only. I'll be increasing it slightly...

**Comment by jpconstantineau** [comment]
@serialx I also remembered that I moved one of the functions from one task to another - although at the same frequency and in parallel, I moved it back to be in the same task but one after the other.  Hopefully this will take care of things (I still had a double press with debouncetime up to 3)

**Comment by jpconstantineau** [comment]
Worked with my board quite a bit more while connected via USB and I have gotten a few more instances of repeated keys (missed all clear).  Finding the exact source of the issue might be challenging. I wonder if completely shutting down BLE when USB is connected would help...

**Comment by jpconstantineau** [comment]
Tested Quickly with Sofle Split Board.  Will be merging.

**Pull request merged**
